name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Trigger deployment
        id: deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Notify successful deployment
        if: ${{ success() && steps.deploy.outcome == 'success' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Success
          title: New version deployed
          description: |
            A new version of fs-pokedex was deployed.
            Commit: ${{ github.sha }}
          nodetail: true
      - name: Notify failed build
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Failure
          title: Build failed
          description: |
            The deployment pipeline failed.
            Commit: ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
